### ISSUE TITLE
Push new release with the windows compatibility additions.

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/pyache#2]
A few windows compatibility fixes were made (#1) but they weren't pushed to pypl
This is requierd for precise windows compatibility (MycroftAI/mycroft-precise#163)
and mycroft core compatibility MycroftAI/mycroft-core#2627

**Comment by NoamDev** [comment]
cc @forslund  @krisgesling @MatthewScholefield

**Comment by krisgesling** [comment]
I've tagged a Github release for the original v0.1.0 and done some minor metadata updates for a v0.2.0 release in PR #3 

Once that's reviewed and merged we can push the release.

**Comment by krisgesling** [comment]
v0.2.0 is now available on PyPI
https://pypi.org/project/pyache/
